name: CI 
 
on: [push] 
 
jobs: 
  ci: 
    runs-on: macos-latest 
 
    steps: 
      - uses: actions/checkout@v2 
      - name: build-and-test-macos 
        run: xcodebuild clean build test -project pokepedia/Pokepedia.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
